id: IE2C97DF6
legacy_id: P008004
ocr_import_info:
  bdrc_scan_id: W25102
  source: bdrc
  ocr_info:
    timestamp: '2020-03-24T17:00:01'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T05:58:57.311574+00:00'
last_modified: 2022-09-02 14:00:03.837900
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25102
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW25102
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རིགས་ཀུན་འདུས་པའི་བདག་ཉིད་འཁོར་ལོའི་མགོན་པོ་མདོ་ཁམས་བརྒྱད་པ་རིན་པོ་ཆེ་དཔལ་ལྡན་ངག་དབང་མི་ཕམ་་་་་སྐལ་བཟང་དོན་བརྒྱུད་ཉི་མ་དགེ་ལེགས་ཕྲིན་ལས་ཀུན་ཁྱབ་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་སྡེའི་རྣམ་པར་ཐར་པའི་རིམ་པ་མདོ་ཙམ་བརྗོད་པ་ཨུཏ་པ།
  author: འབྲོང་པ་སྤྲུལ་སྐུ་ངག་དབང་བློ་གྲོས་འཕྲིན་ལས་མཆོག་གྲུབ།
statistics:
  ocr_word_mean_confidence_index: 0.894268142129377
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3862:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3862
      total_pages: 474
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I3862.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8747493281091422
    legacy_id: v002
  I3861:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3861
      total_pages: 506
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3861.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9168523082479734
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
