id: IE2C97DF6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T17:01:13+00:00'
last_modified: '2022-06-16T05:44:17.003204+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25102
  title: རིགས་ཀུན་འདུས་པའི་བདག་ཉིད་འཁོར་ལོའི་མགོན་པོ་མདོ་ཁམས་བརྒྱད་པ་རིན་པོ་ཆེ་དཔལ་ལྡན་ངག་དབང་མི་ཕམ་་་་་སྐལ་བཟང་དོན་བརྒྱུད་ཉི་མ་དགེ་ལེགས་ཕྲིན་ལས་ཀུན་ཁྱབ་ཕྱོགས་ལས་རྣམ་པར་རྒྱལ་བའི་སྡེའི་རྣམ་པར་ཐར་པའི་རིམ་པ་མདོ་ཙམ་བརྗོད་པ་ཨུཏ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    C5C8:
      image_group_id: I3861
      title: ''
      total_pages: 506
      order: 1
      base_file: C5C8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
